feat: adds new commands and capabilities (sso, custom idp, etc.)
MarcusSchoelzel/btpcflogin pull request #3
Opened 2023-08-15 21:24 UTC by stockbal

Introduction of new commands

2023-08-24 13:14 UTC, MarcusSchoelzel commented on package.json
>    "scripts": {
- Keep the prepare script, as this is automatically called during publish.
- Move the json file to a seperate folder that can be referenced by both folders (src and lib). This makes copying the files obsolete and the dependencies to copyfiles and rimraf aren't needed. And the clean srcipt is not needed.
- Add ts-node to the dev dependencies and start the app in local script from typescript files.

2023-08-24 13:14 UTC, MarcusSchoelzel commented on package.json
> +    "trailingComma": "none",
Don't change the trailingComma setting

2023-08-24 13:14 UTC, MarcusSchoelzel commented on src/util/helper.ts
> +export const exec = util.promisify(child_process.exec);
Remove exec and replace it with spawn

2023-08-24 19:35 UTC, stockbal commented
Requested changes have been applied.

**Note**:
Due to the changing of `exec` to `spawnSync`, [ora](https://www.npmjs.com/package/ora) was chosen a spinner library.

2023-08-25 08:42 UTC, MarcusSchoelzel requested changes
Please move "Origin" from config store to password manger. This makes the connection between the user and the idp clearer. And the step to choose the origin is not needed.

2023-08-25 11:24 UTC, stockbal commented
Adjustments are made.

I also made some other refactorings as well:
- All cf cli calls are now located in a single class module
- singleton exports were removed
- error handler could be moved into cf cli module

2023-08-25 14:13 UTC, MarcusSchoelzel approved these changes

2023-08-25 14:15 UTC, merged